#!/bin/bash
# Job name
#PBS -N BFS
# Output files
#PBS -o ./stdout.o
#PBS -e ./stderr.e
# Queue name
#PBS -q short_cpuQ
# Set the maximum wall time
#PBS -l walltime=02:00:00
# Number of nodes, cores and memory
#PBS -l select=1:ncpus=96:mem=100gb
#PBS -l place=exclhost

# Import modules
module load gcc91 likwid-4.3.4 cmake-3.15.4

cd /home/salvatore.andaloro/CacheMeIfYouCan
scripts/run_runtime_tests.sh